platform :ios, '8.0'
use_frameworks!

project '../SDWebImageWebPCoder'
workspace '../SDWebImageWebPCoder'

target 'SDWebImageWebPCoderTests' do
  pod 'Expecta'
  pod 'SDWebImageWebPCoder', :path => '../'
end
